### ISSUE TITLE
Unable to query same layer multiple times in search settings

### ISSUE THREAD

**Issue by lindsayking** [Esri/live-work-locate#135]
If the same layer is queried multiple times in search settings, the search results in the application display the result from the last query listed in search settings.

Please refer to http://50.18.115.76/LWLissue135 as an example.
For the WORK workflow, which uses webmap fb6babab116c4ddaa4a80b4e4eaecbb0, the "County and Demographic Info" is in the webmap once, but is referenced four times in the config.js for querying different attributes:

````
 SearchSettings: [{
                UnifiedSearch: "true",
                Title: "County and Demographic Info",
                QueryLayerId: "7",
                SearchDisplayTitle: "Personal Income Tax",
                SearchDisplayFields: "${SITENAME} / ${PERSINCTX}",
                SearchExpression: "UPPER(SITENAME) LIKE UPPER('${0}%') OR UPPER(COUNTY) LIKE UPPER('${0}%')"
            }, {
                UnifiedSearch: "true",
                Title: "County and Demographic Info",
                QueryLayerId: "7",
                SearchDisplayTitle: "Median Household Income",
                SearchDisplayFields: "${SITENAME} / ${COUNTY} / ${MEDHOUSINC}",
                SearchExpression: "UPPER(SITENAME) LIKE UPPER('${0}%') OR UPPER(COUNTY) LIKE UPPER('${0}%')"
            }, {
                UnifiedSearch: "true",
                Title: "County and Demographic Info",
                QueryLayerId: "7",
                SearchDisplayTitle: "Labor Force",
                SearchDisplayFields: "${SITENAME} / ${LABORFORCE}",
                SearchExpression: "UPPER(SITENAME) LIKE UPPER('${0}%') OR UPPER(COUNTY) LIKE UPPER('${0}%')"
            }, {
                UnifiedSearch: "true",
                Title: "County and Demographic Info",
                QueryLayerId: "7",
                SearchDisplayTitle: "Unemployment",
                SearchDisplayFields: "${SITENAME} / ${UNEMPLOY}",
                SearchExpression: "UPPER(SITENAME) LIKE UPPER('${0}%') OR UPPER(COUNTY) LIKE UPPER('${0}%')"
            }]
````

Rather than showing the four different attributes in the search result, "Unemployment" displays four times.
![image](https://cloud.githubusercontent.com/assets/4316336/7398249/b323d468-ee62-11e4-9e6f-cc7dbf0a7754.png)

(As a workaround, the layer can be added to the webmap multiple times and given different names.  The LIVE workflow at the URL above is an example of this.)

**Comment by lindsayking** [comment]
@CTLocalGovTeam   What are your thoughts on this issue?

**Comment by CTLocalGovTeam** [comment]
@lindsayking We are analyzing this behavior and will provide findings early next week.

**Comment by CTLocalGovTeam** [comment]
@lindsayking,
We investigated and found this was because the search settings were being tracked on a per layer basis in the app and it was getting overridden when the same layer was configured more than once and only the last setting was retained. This caused the search to be executed/displayed as many times as configured, but with the same settings that was read last.

This was fixed by a minor code change in mapSettings.js. The app now tracks search settings separately. A diff is shown below to help you visualize the magnitude of code change. 

![1](https://cloud.githubusercontent.com/assets/2959186/7586473/df42cdb6-f8ca-11e4-94f7-4add3d38c190.png)
![2](https://cloud.githubusercontent.com/assets/2959186/7586474/df4a66fc-f8ca-11e4-82d9-3c1d9060d305.png)
![3](https://cloud.githubusercontent.com/assets/2959186/7586475/df4a8d12-f8ca-11e4-93f9-d4d31cb49ffe.png)
![4](https://cloud.githubusercontent.com/assets/2959186/7586476/df4f87c2-f8ca-11e4-9235-7bf70fb0eef6.png)

**Comment by CTLocalGovTeam** [comment]
@lindsayking, please let us know if you have any questions and how you'd like to proceed further on this.

**Comment by LindsayThomas** [comment]
@lindsayking have you tested this fix specifically?

**Comment by lindsayking** [comment]
@LindsayThomas Yes, this has been tested.  This adjustment in MapSettings.js fixes the issue.
